### ISSUE TITLE
404 on first login

### ISSUE THREAD

**Issue by plocket** [ckingbailey/publiccode-pusher#9]
Not sure if it'll happen on further loads. 

On the add-publiccode-yml branch after first installing the project [and running `npm start` in a separate terminal with proper behavior]:
1. `npx serve`
1. Click on 'client' folder
1. [Edit: Click to authorize project]
1. Enter password
1. [Click login]
1. Get error:
   1. Visible on page: 'Cannot GET /'
   1. In console:
      1. Failed to load resource: the server responded with a status of 404 (Not Found)
      1. Also an error for the favicon: 'because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.'

[Maybe the password was wrong, though I was pretty sure of it. Maybe something else is wrong. Not sure.]

**Comment by plocket** [comment]
Next attempted:
1. Went back and clicked on 'client' folder
1. Clicked on 'log in'
1. "GET http://localhost:3000/?code... (Not Found)"
1. Following that link led to "github.com/login/oauth/authorize?..." as the initiator in the network tab.

No idea if any of that is useful information.

**Comment by plocket** [comment]
Next attempt:
1. Restart local server
1. Click on 'client' folder
1. Click on 'login'
1. Page showed same text
1. Console error: Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by plocket** [comment]
I do have another terminal window where I ran `npm start` that is 'listening on port 3000'.

**Comment by ckingbailey** [comment]
add-publiccode-yaml is not an active branch

**Comment by plocket** [comment]
Dang, I've been looking at the wrong branch. Closing for now.
